### ISSUE TITLE
 Error while running locally

### ISSUE THREAD

**Issue by Cristyander** [wavesplatform/WavesGUI#1373]
I am trying to run the wallet locally plus this one presenting the following errors after "npm run server". How to correct them?

C:\APPs\wavesheroku\WavesGUI
λ npm run server

> waves-client@1.3.3 server C:\APPs\wavesheroku\WavesGUI
> npm run build && node server

> waves-client@1.3.3 build C:\APPs\wavesheroku\WavesGUI
> tsc -p ./ && gulp all

[23:17:37] Using gulpfile C:\APPs\wavesheroku\WavesGUI\gulpfile.js
[23:17:37] Starting 'clean'...
[23:17:37] Finished 'clean' after 499 ms
[23:17:37] Starting 'data-service'...
[23:17:56] Finished 'data-service' after 19 s
[23:17:56] Starting 'templates'...
[23:17:56] Starting 'concat-develop-sources'...
[23:17:56] Starting 'concat-develop-vendors'...
[23:17:56] Starting 'less'...
[23:17:59] Finished 'less' after 2.16 s
[23:17:59] Starting 'concat-style'...
[23:17:59] Starting 'electron-debug'...
[23:18:01] Finished 'concat-style' after 2.04 s
[23:18:05] Finished 'concat-develop-vendors' after 8.7 s
[23:18:19] Finished 'templates' after 22 s
[23:18:19] Finished 'concat-develop-sources' after 23 s
[23:18:19] Starting 'concat-develop'...
[23:18:19] Finished 'concat-develop' after 142 μs
[23:18:19] Starting 'babel'...
[23:18:19] Starting 'downloadLocales'...
[BABEL] Note: The code generator has deoptimised the styling of "C:/APPs/wavesheroku/WavesGUI/dist/tmp/js/bundle.js" as it exceeds the max of "500KB".
Locales did not loaded: Error: Client network socket disconnected before secure TLS connection was established
[23:18:37] Finished 'downloadLocales' after 18 s
[23:18:37] Starting 'copy-web-testnet-normal'...
[23:18:37] Starting 'copy-web-testnet-min'...
[23:18:37] Starting 'copy-web-mainnet-normal'...
[23:18:37] Starting 'copy-web-mainnet-min'...
[23:18:37] Starting 'copy-desktop-testnet-normal'...
[23:18:37] Starting 'copy-desktop-testnet-min'...
[23:18:37] Starting 'copy-desktop-mainnet-normal'...
[23:18:37] Starting 'copy-desktop-mainnet-min'...
[23:18:37] 'copy-web-testnet-normal' errored after 50 ms
[23:18:37] Error: ENOENT: no such file or directory, lstat 'C:\APPs\wavesheroku\WavesGUI\dist\locale'
[23:18:37] 'copy-web-testnet-min' errored after 54 ms
[23:18:37] Error: ENOENT: no such file or directory, lstat 'C:\APPs\wavesheroku\WavesGUI\dist\locale'
[23:18:37] 'copy-web-mainnet-normal' errored after 56 ms
[23:18:37] Error: ENOENT: no such file or directory, lstat 'C:\APPs\wavesheroku\WavesGUI\dist\locale'
[23:18:37] 'copy-web-mainnet-min' errored after 58 ms
[23:18:37] Error: ENOENT: no such file or directory, lstat 'C:\APPs\wavesheroku\WavesGUI\dist\locale'
[23:18:37] 'copy-desktop-testnet-normal' errored after 61 ms
[23:18:37] Error: ENOENT: no such file or directory, lstat 'C:\APPs\wavesheroku\WavesGUI\dist\locale'
[23:18:37] 'copy-desktop-testnet-min' errored after 59 ms
[23:18:37] Error: ENOENT: no such file or directory, lstat 'C:\APPs\wavesheroku\WavesGUI\dist\locale'
[23:18:37] 'copy-desktop-mainnet-normal' errored after 55 ms
[23:18:37] Error: ENOENT: no such file or directory, lstat 'C:\APPs\wavesheroku\WavesGUI\dist\locale'
[23:18:37] 'copy-desktop-mainnet-min' errored after 52 ms
[23:18:37] Error: ENOENT: no such file or directory, lstat 'C:\APPs\wavesheroku\WavesGUI\dist\locale'
[23:18:37] Finished 'babel' after 18 s
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 52.218.52.44:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! waves-client@1.3.3 build: `tsc -p ./ && gulp all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the waves-client@1.3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\CristySamara\AppData\Roaming\npm-cache\_logs\2019-06-12T02_18_40_456Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! waves-client@1.3.3 server: `npm run build && node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the waves-client@1.3.3 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\CristySamara\AppData\Roaming\npm-cache\_logs\2019-06-12T02_18_40_571Z-debug.log

C:\APPs\wavesheroku\WavesGUI
λ node -v
v10.16.0

**Comment by tsigel** [comment]
U can't download files with translations for i18next. Try again or debug u connection.

`Locales did not loaded: Error: Client network socket disconnected before secure TLS connection was established`
