### ISSUE TITLE
TypeError: http2_1.createSecureServer is not a function

### ISSUE THREAD

**Issue by arsen3d** [wavesplatform/WavesGUI#714]
error after running
```
npm run i
npm run server

[15:03:31] Finished 'all' after 1.26 μs
/Users/arsen/WebstormProjects/WavesGUI/server.js:42
    const server = http2_1.createSecureServer({ key: privateKey, cert: certificate });
                           ^

TypeError: http2_1.createSecureServer is not a function
    at createMyServer (/Users/arsen/WebstormProjects/WavesGUI/server.js:42:28)
    at Object.<anonymous> (/Users/arsen/WebstormProjects/WavesGUI/server.js:56:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! waves-client@1.0.0-beta.38 server: `npm run build && node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the waves-client@1.0.0-beta.38 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arsen/.npm/_logs/2018-06-02T22_03_32_253Z-debug.log
imac5k2015:WavesGUI arsen$ npm run server

**Comment by arsen3d** [comment]
I had wrong node version
```
imac5k2015:WavesGUI arsen$ node -v
v8.6.0
imac5k2015:WavesGUI arsen$ node server
module.js:529
    throw err;
    ^

Error: Cannot find module 'http2'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/arsen/WebstormProjects/WavesGUI/server.js:3:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
imac5k2015:WavesGUI arsen$ n stable
imac5k2015:WavesGUI arsen$ node server
Listen port 8080...
Available urls:
https://localhost:8080
(node:63400) ExperimentalWarning: The http2 module is an experimental API.
